### PR TITLE
Plugin updates from Aug-Dec 2015

### PR DESCRIPTION
**Pull request by ssundheim**

### CODE REVIEW

**Comment by ssundheim** [comment]
@jpasichnyk Howdy, P. Can you do this merge this pull request?

**Comment by ssundheim** [comment]
@jpasichnyk  Howdy, P. Can you merge this in?

**Comment by aallfredo** [comment]
@ssundheim i got it

**Comment by aallfredo** [comment]
@ssundheim thanks for getting this back to date.

**Pull request merged**
